/*
  # Meal Prep App — Initial Schema

  ## New Tables

  ### profiles
  - id (uuid, references auth.users)
  - full_name (text)
  - avatar_url (text)
  - dietary_preferences (text[]) — e.g. ['vegan', 'gluten-free']
  - calorie_goal (int)
  - onesignal_player_id (text) — for push notification targeting
  - created_at, updated_at (timestamptz)

  ### meal_plans
  - id (uuid)
  - user_id (uuid, references profiles)
  - title (text)
  - description (text)
  - meals (jsonb) — array of meal objects generated by AI
  - week_start (date)
  - created_at (timestamptz)

  ### shopping_lists
  - id (uuid)
  - user_id (uuid, references profiles)
  - meal_plan_id (uuid, nullable, references meal_plans)
  - title (text)
  - items (jsonb) — array of {name, qty, unit, category, checked}
  - created_at, updated_at (timestamptz)

  ### weekly_planner
  - id (uuid)
  - user_id (uuid, references profiles)
  - week_start (date)
  - plan (jsonb) — {monday:{breakfast,lunch,dinner}, tuesday:..., ...}
  - created_at, updated_at (timestamptz)

  ## Security
  - RLS enabled on all tables
  - Users can only read/write their own rows
*/

-- profiles
CREATE TABLE IF NOT EXISTS profiles (
  id uuid PRIMARY KEY REFERENCES auth.users ON DELETE CASCADE,
  full_name text DEFAULT '',
  avatar_url text DEFAULT '',
  dietary_preferences text[] DEFAULT '{}',
  calorie_goal int DEFAULT 2000,
  onesignal_player_id text DEFAULT '',
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own profile"
  ON profiles FOR SELECT
  TO authenticated
  USING (auth.uid() = id);

CREATE POLICY "Users can insert own profile"
  ON profiles FOR INSERT
  TO authenticated
  WITH CHECK (auth.uid() = id);

CREATE POLICY "Users can update own profile"
  ON profiles FOR UPDATE
  TO authenticated
  USING (auth.uid() = id)
  WITH CHECK (auth.uid() = id);

-- meal_plans
CREATE TABLE IF NOT EXISTS meal_plans (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  title text NOT NULL DEFAULT '',
  description text DEFAULT '',
  meals jsonb DEFAULT '[]',
  week_start date,
  created_at timestamptz DEFAULT now()
);

ALTER TABLE meal_plans ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own meal plans"
  ON meal_plans FOR SELECT
  TO authenticated
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own meal plans"
  ON meal_plans FOR INSERT
  TO authenticated
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own meal plans"
  ON meal_plans FOR UPDATE
  TO authenticated
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can delete own meal plans"
  ON meal_plans FOR DELETE
  TO authenticated
  USING (auth.uid() = user_id);

-- shopping_lists
CREATE TABLE IF NOT EXISTS shopping_lists (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  meal_plan_id uuid REFERENCES meal_plans(id) ON DELETE SET NULL,
  title text NOT NULL DEFAULT 'Shopping List',
  items jsonb DEFAULT '[]',
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

ALTER TABLE shopping_lists ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own shopping lists"
  ON shopping_lists FOR SELECT
  TO authenticated
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own shopping lists"
  ON shopping_lists FOR INSERT
  TO authenticated
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own shopping lists"
  ON shopping_lists FOR UPDATE
  TO authenticated
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can delete own shopping lists"
  ON shopping_lists FOR DELETE
  TO authenticated
  USING (auth.uid() = user_id);

-- weekly_planner
CREATE TABLE IF NOT EXISTS weekly_planner (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  week_start date NOT NULL,
  plan jsonb DEFAULT '{}',
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  UNIQUE(user_id, week_start)
);

ALTER TABLE weekly_planner ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own weekly planner"
  ON weekly_planner FOR SELECT
  TO authenticated
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own weekly planner"
  ON weekly_planner FOR INSERT
  TO authenticated
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own weekly planner"
  ON weekly_planner FOR UPDATE
  TO authenticated
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can delete own weekly planner"
  ON weekly_planner FOR DELETE
  TO authenticated
  USING (auth.uid() = user_id);
